version: '3.8'

services:
  flask-app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - FLASK_ENV=production
      - GUNICORN_WORKERS=4
    networks:
      - app-network
    volumes:
      - .:/app  # 挂载应用代码（开发模式）
    ports:
      - "8000:8000"
    restart: unless-stopped

  

networks:
  app-network:
    driver: bridge
