version: '3.8'

services:
  flask-app:
    image: "docker.cnb.cool/netcat1/images/fs-fav:6f5c8b37feae2ef5c99ff155100dcec9559d5344"
    environment:
      - FLASK_ENV=production
      - GUNICORN_WORKERS=4
    networks:
      - app-network
    volumes:
      - .:/app  # 挂载应用代码（开发模式）
    ports:
      - "8000:8000"
    restart: unless-stopped

  

networks:
  app-network:
    driver: bridge
